# Generated by Django 6.0.4 on 2026-04-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان گلوله')),
                ('text', models.TextField(verbose_name='متن گلوله')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'گلوله درباره ما',
                'verbose_name_plural': 'گلوله\u200cهای درباره ما',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnatomyLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام لایه')),
                ('info_text', models.TextField(verbose_name='توضیح لایه')),
                ('depth', models.IntegerField(verbose_name='عمق (عدد)')),
                ('info_id', models.CharField(help_text='مثلاً 1,2,3,4', max_length=10, verbose_name='شناسه info')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'لایه ایزوگام',
                'verbose_name_plural': 'لایه\u200cهای ایزوگام',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مزیت')),
                ('description', models.TextField(verbose_name='توضیح مزیت')),
                ('svg_icon', models.TextField(help_text='کد SVG کامل (مثلاً <svg>...</svg>)', verbose_name='کد SVG آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'مزیت',
                'verbose_name_plural': 'مزایا',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=10, verbose_name='شماره مرحله (مثلاً 01)')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مرحله')),
                ('description', models.TextField(verbose_name='توضیح مرحله')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'مرحله همکاری',
                'verbose_name_plural': 'مراحل همکاری',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, verbose_name='شماره سرویس (مثلاً 01)')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سرویس')),
                ('description', models.TextField(verbose_name='توضیح سرویس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255, verbose_name='عنوان بزرگ هیرو')),
                ('hero_subtitle', models.CharField(max_length=255, verbose_name='زیرعنوان هیرو')),
                ('hero_description', models.TextField(verbose_name='توضیحات هیرو')),
                ('hero_cta_primary_text', models.CharField(max_length=100, verbose_name='متن دکمه اصلی هیرو')),
                ('hero_cta_secondary_text', models.CharField(max_length=100, verbose_name='متن دکمه ثانویه هیرو')),
                ('phone_direct', models.CharField(max_length=20, verbose_name='شماره تماس مستقیم')),
                ('footer_copyright', models.CharField(default='© تمامی حقوق برای سپید بام محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت فوتر')),
                ('about_title', models.CharField(max_length=255, verbose_name='عنوان درباره ما')),
                ('about_text1', models.TextField(verbose_name='پاراگراف اول درباره ما')),
                ('about_text2', models.TextField(verbose_name='پاراگراف دوم درباره ما')),
                ('about_quality_core_title', models.CharField(max_length=100, verbose_name='عنوان دایره کیفیت')),
                ('about_quality_core_text', models.TextField(verbose_name='متن دایره کیفیت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='عدد آمار')),
                ('label', models.CharField(max_length=200, verbose_name='توضیح آمار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمارها',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='پردازش شده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='توضیح پروژه'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(max_length=100, verbose_name='نوع پروژه'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=100, verbose_name='نوع کاربری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('done', 'تحویل شده'), ('progress', 'در دست اجرا')], default='done', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surface_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='سطح اجرا'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان پروژه'),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن آیتم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'آیتم خدمت',
                'verbose_name_plural': 'آیتم\u200cهای خدمات',
                'ordering': ['order'],
            },
        ),
    ]
