# Generated by Django 5.2 on 2026-05-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutbullet_anatomylayer_feature_processstep_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='stats/', verbose_name='تصویر کاور'),
        ),
    ]
