# Generated by Django 5.2 on 2026-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stat_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('features', models.TextField(blank=True, help_text='هر ویژگی را در یک خط بنویسید', verbose_name='ویژگی\u200cها')),
                ('thickness', models.CharField(blank=True, max_length=50, verbose_name='ضخامت')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='وزن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
