# Generated by Django 5.2.14 on 2026-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('role', models.CharField(max_length=150, verbose_name='سمت')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی کوتاه')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='عکس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(max_length=255, verbose_name='زیرعنوان هیرو (ادامه عنوان)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(max_length=255, verbose_name='عنوان برجسته هیرو (بخش رنگی)'),
        ),
    ]
