# Generated by Django 5.2.14 on 2026-06-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('media_type', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو')], default='image', max_length=10, verbose_name='نوع رسانه')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر / پوستر ویدیو')),
                ('video_url', models.URLField(blank=True, help_text='لینک YouTube یا Aparat', verbose_name='لینک ویدیو')),
                ('caption', models.TextField(blank=True, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='برجسته (سایز بزرگ)')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'گالری رسانه',
                'ordering': ['order', '-id'],
            },
        ),
    ]
