# Generated by Django 5.2.14 on 2026-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_media_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_label',
            field=models.CharField(blank=True, default='سال تجربه', max_length=80, verbose_name='برچسب نشان درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge_num',
            field=models.CharField(blank=True, default='۱۵+', max_length=20, verbose_name='عدد نشان درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_eyebrow',
            field=models.CharField(blank=True, default='درباره برند فراز بام', max_length=120, verbose_name='برچسب بخش درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='تصویر بخش درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat_1_label',
            field=models.CharField(blank=True, default='پروژه موفق', max_length=80, verbose_name='آمار کوچک ۱ (برچسب)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat_1_value',
            field=models.CharField(blank=True, default='۱۲۰۰+', max_length=30, verbose_name='آمار کوچک ۱ (عدد)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat_2_label',
            field=models.CharField(blank=True, default='رضایت مشتری', max_length=80, verbose_name='آمار کوچک ۲ (برچسب)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat_2_value',
            field=models.CharField(blank=True, default='۹۸٪', max_length=30, verbose_name='آمار کوچک ۲ (عدد)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat_3_label',
            field=models.CharField(blank=True, default='پشتیبانی', max_length=80, verbose_name='آمار کوچک ۳ (برچسب)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_stat_3_value',
            field=models.CharField(blank=True, default='۲۴/۷', max_length=30, verbose_name='آمار کوچک ۳ (عدد)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='activity_area',
            field=models.CharField(blank=True, default='سراسر کشور', max_length=200, verbose_name='محدوده فعالیت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anatomy_desc',
            field=models.TextField(blank=True, default='کیفیت ایزوگام تنها به ظاهر آن محدود نیست. عملکرد نهایی، حاصل همکاری چند لایه مکمل است.', verbose_name='توضیح بخش آناتومی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anatomy_eyebrow',
            field=models.CharField(blank=True, default='ساختار لایه\u200cای ایزوگام', max_length=120, verbose_name='برچسب بخش آناتومی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anatomy_hint_1',
            field=models.TextField(blank=True, default='روی هر لایه توقف کنید تا عملکرد دقیق آن را ببینید.', verbose_name='راهنمای آناتومی ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anatomy_hint_2',
            field=models.TextField(blank=True, default='با اسکرول، فاصله لایه\u200cها نمایان می\u200cشود تا ساختار درونی را بهتر درک کنید.', verbose_name='راهنمای آناتومی ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anatomy_hint_3',
            field=models.TextField(blank=True, default='این ساختار چندلایه همان چیزی است که از سازه در برابر نفوذ و فرسایش محافظت می\u200cکند.', verbose_name='راهنمای آناتومی ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anatomy_title',
            field=models.CharField(blank=True, default='هر لایه، یک نقش حیاتی در ماندگاری نهایی', max_length=200, verbose_name='عنوان بخش آناتومی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='تصویر پس\u200cزمینه سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_desc',
            field=models.TextField(blank=True, default='فرم زیر را پر کنید تا در اسرع وقت با شما تماس بگیریم.', verbose_name='توضیح بخش تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_eyebrow',
            field=models.CharField(blank=True, default='تماس با ما', max_length=120, verbose_name='برچسب بخش تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_desc',
            field=models.TextField(blank=True, default='اطلاعات پروژه خود را وارد کنید.', verbose_name='توضیح فرم تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title',
            field=models.CharField(blank=True, default='فرم درخواست', max_length=200, verbose_name='عنوان فرم تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_info_text',
            field=models.TextField(blank=True, default='برای مشاوره تخصصی و بازدید از محل پروژه با ما در تماس باشید.', verbose_name='متن باکس اطلاعات تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_info_title',
            field=models.CharField(blank=True, default='اطلاعات تماس', max_length=200, verbose_name='عنوان باکس اطلاعات تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(blank=True, default='درخواست مشاوره رایگان', max_length=200, verbose_name='عنوان بخش تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='تصویر پس\u200cزمینه CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_btn_primary',
            field=models.CharField(blank=True, default='ثبت درخواست', max_length=100, verbose_name='متن دکمه اصلی CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_btn_secondary',
            field=models.CharField(blank=True, default='تماس مستقیم', max_length=100, verbose_name='متن دکمه ثانویه CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_desc',
            field=models.TextField(blank=True, default='همین حالا درخواست مشاوره رایگان ثبت کنید.', verbose_name='توضیح CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(blank=True, default='آماده شروع پروژه عایق\u200cکاری هستید؟', max_length=200, verbose_name='عنوان CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_desc',
            field=models.TextField(blank=True, default='پاسخ سوالات متداول درباره عایق\u200cکاری و خدمات ما.', verbose_name='توضیح بخش FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_eyebrow',
            field=models.CharField(blank=True, default='سوالات متداول', max_length=120, verbose_name='برچسب بخش FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_title',
            field=models.CharField(blank=True, default='پاسخ به پرسش\u200cهای رایج', max_length=200, verbose_name='عنوان بخش FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_desc',
            field=models.TextField(blank=True, default='مزایای همکاری با ما در یک نگاه.', verbose_name='توضیح بخش مزایا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_eyebrow',
            field=models.CharField(blank=True, default='مزایا', max_length=120, verbose_name='برچسب بخش مزایا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_title',
            field=models.CharField(blank=True, default='چرا فراز بام؟', max_length=200, verbose_name='عنوان بخش مزایا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_brand_name',
            field=models.CharField(blank=True, default='فراز بام', max_length=80, verbose_name='نام برند در فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(blank=True, default='عایق\u200cکاری حرفه\u200cای سقف', max_length=200, verbose_name='شعار فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_desc',
            field=models.TextField(blank=True, default='گالری تصاویر از اجرای پروژه\u200cهای مختلف.', verbose_name='توضیح بخش گالری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_eyebrow',
            field=models.CharField(blank=True, default='گالری', max_length=120, verbose_name='برچسب بخش گالری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_title',
            field=models.CharField(blank=True, default='تصاویر پروژه\u200cها', max_length=200, verbose_name='عنوان بخش گالری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_brand_name',
            field=models.CharField(blank=True, default='فراز بام،', max_length=80, verbose_name='نام برند در عنوان هیرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='برند تخصصی عایق\u200cکاری رطوبتی', max_length=120, verbose_name='برچسب بالای هیرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو (هدر و فوتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_desc',
            field=models.TextField(blank=True, default='مسیر شفاف و مرحله\u200cبه\u200cمرحله برای اجرای پروژه شما.', verbose_name='توضیح بخش فرآیند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_eyebrow',
            field=models.CharField(blank=True, default='فرآیند همکاری', max_length=120, verbose_name='برچسب بخش فرآیند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_title',
            field=models.CharField(blank=True, default='از مشاوره تا تحویل پروژه', max_length=200, verbose_name='عنوان بخش فرآیند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_desc',
            field=models.TextField(blank=True, default='محصولات متناسب با نوع سقف، کاربری و شرایط اقلیمی.', verbose_name='توضیح بخش محصولات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_eyebrow',
            field=models.CharField(blank=True, default='محصولات', max_length=120, verbose_name='برچسب بخش محصولات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_title',
            field=models.CharField(blank=True, default='راه\u200cحل\u200cهای عایق\u200cکاری متنوع', max_length=200, verbose_name='عنوان بخش محصولات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_desc',
            field=models.TextField(blank=True, default='نمونه\u200cهایی از پروژه\u200cهای موفق عایق\u200cکاری.', verbose_name='توضیح بخش پروژه\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_eyebrow',
            field=models.CharField(blank=True, default='نمونه کارها', max_length=120, verbose_name='برچسب بخش پروژه\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_title',
            field=models.CharField(blank=True, default='پروژه\u200cهای اجراشده', max_length=200, verbose_name='عنوان بخش پروژه\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='response_time',
            field=models.CharField(blank=True, default='کمتر از ۲۴ ساعت', max_length=100, verbose_name='زمان پاسخگویی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_desc',
            field=models.TextField(blank=True, default='از مشاوره تا اجرا و پشتیبانی.', verbose_name='توضیح بخش خدمات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_eyebrow',
            field=models.CharField(blank=True, default='خدمات', max_length=120, verbose_name='برچسب بخش خدمات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(blank=True, default='خدمات تخصصی عایق\u200cکاری', max_length=200, verbose_name='عنوان بخش خدمات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stats_desc',
            field=models.TextField(blank=True, default='هر عدد پشت آن سال\u200cها تجربه، پروژه\u200cهای موفق و اعتماد مشتریان است.', verbose_name='توضیح بخش آمار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stats_eyebrow',
            field=models.CharField(blank=True, default='دستاوردهای فراز بام', max_length=120, verbose_name='برچسب بخش آمار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stats_title',
            field=models.CharField(blank=True, default='اعداد، روایت\u200cگر کیفیت ماست', max_length=200, verbose_name='عنوان بخش آمار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_desc',
            field=models.TextField(blank=True, default='تیمی از مهندسان و اجراکنندگان با تجربه در عایق\u200cکاری سقف.', verbose_name='توضیح بخش تیم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_eyebrow',
            field=models.CharField(blank=True, default='تیم ما', max_length=120, verbose_name='برچسب بخش تیم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_title',
            field=models.CharField(blank=True, default='متخصصان فراز بام', max_length=200, verbose_name='عنوان بخش تیم'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_chip_1',
            field=models.CharField(blank=True, default='اجرای اصولی و استاندارد', max_length=120, verbose_name='چیپ اعتماد ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_chip_2',
            field=models.CharField(blank=True, default='دوام بالا در شرایط سخت اقلیمی', max_length=120, verbose_name='چیپ اعتماد ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_chip_3',
            field=models.CharField(blank=True, default='مشاوره متناسب با نوع پروژه', max_length=120, verbose_name='چیپ اعتماد ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_desc',
            field=models.TextField(blank=True, default='نمونه\u200cهای واقعی از اجرای پروژه\u200cهای عایق\u200cکاری.', verbose_name='توضیح بخش ویدیو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_eyebrow',
            field=models.CharField(blank=True, default='ویدیوها', max_length=120, verbose_name='برچسب بخش ویدیو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_title',
            field=models.CharField(blank=True, default='فرآیند اجرا را ببینید', max_length=200, verbose_name='عنوان بخش ویدیو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_quality_core_text',
            field=models.TextField(blank=True, default='هسته اصلی', verbose_name='متن دایره کیفیت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_quality_core_title',
            field=models.CharField(blank=True, default='کیفیت', max_length=100, verbose_name='عنوان دایره کیفیت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text1',
            field=models.TextField(blank=True, default='', verbose_name='پاراگراف اول درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text2',
            field=models.TextField(blank=True, default='', verbose_name='پاراگراف دوم درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(blank=True, default='کیفیت، از نگاه مهندسی تا اجرا', max_length=255, verbose_name='عنوان درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© تمامی حقوق برای فراز بام محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت فوتر'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_primary_text',
            field=models.CharField(blank=True, default='دریافت مشاوره تخصصی', max_length=100, verbose_name='متن دکمه اصلی هیرو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_secondary_text',
            field=models.CharField(blank=True, default='مشاهده نمونه پروژه\u200cها', max_length=100, verbose_name='متن دکمه ثانویه هیرو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True, default='ایزوگام را سیستم مهندسی حفاظت سقف می\u200cدانیم؛ برای عمر بیشتر سازه، جلوگیری از رطوبت و کیفیت پایدار.', verbose_name='توضیحات هیرو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='در برابر آب، گرما و فرسایش', max_length=255, verbose_name='زیرعنوان هیرو (ادامه عنوان)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='سپر مطمئن سقف', max_length=255, verbose_name='عنوان برجسته هیرو (بخش رنگی)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_direct',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس مستقیم'),
        ),
    ]
