# Generated by Django 5.2.17 on 2026-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_cms_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anatomylayer',
            options={'ordering': ['order', 'info_id'], 'verbose_name': 'لایه ایزوگام', 'verbose_name_plural': 'لایه\u200cهای ایزوگام'},
        ),
        migrations.AlterField(
            model_name='anatomylayer',
            name='depth',
            field=models.IntegerField(editable=False, help_text='خودکار از شناسه لایه (۱ تا ۴) تنظیم می\u200cشود.', verbose_name='عمق انیمیشن'),
        ),
        migrations.AlterField(
            model_name='anatomylayer',
            name='info_id',
            field=models.CharField(help_text='فقط ۱، ۲، ۳ یا ۴ — رنگ و عمق ۳D بر اساس این شناسه است.', max_length=10, verbose_name='شناسه لایه'),
        ),
        migrations.AlterField(
            model_name='anatomylayer',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
