# Generated by Django 5.2.17 on 2026-10-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_anatomylayer_options_alter_anatomylayer_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, default='فراز بام، برند تخصصی ایزوگام و عایق\u200cکاری رطوبتی با اجرای حرفه\u200cای، دوام بالا، مقاومت در برابر گرما و سرما و مشاوره تخصصی پروژه.', verbose_name='توضیحات SEO'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/seo/', verbose_name='تصویر Open Graph'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, default='فراز بام | ایزوگام و عایق\u200cکاری تخصصی', max_length=255, verbose_name='عنوان SEO'),
        ),
    ]
